// Hero Section
export const brands = [
    {
      src: "/brand-Logos/ritter-sport.svg",
      alt: "Ritter Sport",
    },
    {
      src: "/brand-Logos/Nike.svg",
      alt: "Nike",
    },
    {
      src: "/brand-Logos/Adidas.svg",
      alt: "Adidas",
    },
    {
      src: "/brand-Logos/New-Holland.svg",
      alt: "New Holland",
    },
  ];

// Live Auctions Section
export const AUCTIONS = [
    {
        image: "/auctions/auction-image1.png",
        title: "Vulputate felis purus viverra morbi feget",
        price: "2.55 ETH",
        timeLeft: "22:59 min left",
        bidders: ["/avatars/01.png", "/avatars/02.png", "/avatars/03.png"],
        biddersCount: 35,
        liked: true,
        likes: 120,
    },
    {
        image: "/auctions/auction-image2.png",
        title: "Dui accumsan leo vestibulum ornare eu",
        price: "3.19 ETH",
        timeLeft: "2:41 min left",
        bidders: ["/avatars/04.png", "/avatars/05.png", "/avatars/06.png"],
        biddersCount: 101,
        liked: false,
        likes: 570,
    },
    {
        image: "/auctions/auction-image3.png",
        title: "Senectus adipiscing nascetur accumsan etiam",
        price: "1.11 ETH",
        timeLeft: "22:59 min left",
        bidders: ["/avatars/07.png", "/avatars/01.png", "/avatars/02.png"],
        biddersCount: 12,
        liked: true,
        likes: 98,
    },
    {
        image: "/auctions/auction-image1.png",
        title: "Mattis at diam lorem nam sed sociis",
        price: "1.63 ETH",
        timeLeft: "37:01 min left",
        bidders: ["/avatars/01.png", "/avatars/02.png", "/avatars/03.png"],
        biddersCount: 19,
        liked: true,
        likes: 146,
    },
    {
        image: "/auctions/auction-image2.png",
        title: "Digital Art Collection #156",
        price: "4.20 ETH",
        timeLeft: "12:15 min left",
        bidders: ["/avatars/04.png", "/avatars/05.png", "/avatars/06.png"],
        biddersCount: 25,
        liked: false,
        likes: 230,
    },
    {
        image: "/auctions/auction-image3.png",
        title: "Crypto Punk Generation Y",
        price: "2.80 ETH",
        timeLeft: "15:45 min left",
        bidders: ["/avatars/07.png", "/avatars/01.png", "/avatars/02.png"],
        biddersCount: 42,
        liked: true,
        likes: 315,
    },
]

// Popular Auctions Section
export const popularAuctions = [
    {
        image: "/popularAuctions/image.png",
        title: "Vulputate felis purus viverra morbi feget",
        price: "2.55 ETH",
        timeLeft: "22:59 min left",
        biddersCount: 35,
        liked: true,
        likes: 120,
    },
    {
        image: "/popularAuctions/image-1.png",
        title: "Dui accumsan leo vestibulum ornare eu",
        price: "3.19 ETH",
        timeLeft: "2:41 min left",
        biddersCount: 101,
        liked: false,
        likes: 570,
    },
    {
        image: "/popularAuctions/image-2.png",
        title: "Senectus adipiscing nascetur accumsan etiam",
        price: "1.11 ETH",
        timeLeft: "22:59 min left",
        biddersCount: 12,
        liked: true,
        likes: 98,
    },
    {
        image: "/popularAuctions/image-3.png",
        title: "Senectus adipiscing nascetur accumsan etiam",
        price: "1.11 ETH",
        timeLeft: "22:59 min left",
        biddersCount: 12,
        liked: true,
        likes: 98,
    },
    {
        image: "/popularAuctions/image-4.png",
        title: "Senectus adipiscing nascetur accumsan etiam",
        price: "1.11 ETH",
        timeLeft: "22:59 min left",
        biddersCount: 12,
        liked: true,
        likes: 98,
    },
    {
        image: "/popularAuctions/image-5.png",
        title: "Senectus adipiscing nascetur accumsan etiam",
        price: "1.11 ETH",
        timeLeft: "22:59 min left",
        biddersCount: 12,
        liked: true,
        likes: 98,
    },
]

// Marquee Section
export const nfts = [
    { price: "3.25", image: "/marquee/image-1.png" },
    { price: "3.62", image: "/marquee/image-2.png" },
    { price: "3.82", image: "/marquee/image-3.png" },
    { price: "2.77", image: "/marquee/image-4.png" },
    { price: "1.61", image: "/marquee/image-5.png" },
    { price: "2.29", image: "/marquee/image-6.png" },
    { price: "2.03", image: "/marquee/image-7.png" },
    { price: "3.69", image: "/marquee/image-8.png" },
    { price: "1.49", image: "/marquee/image-9.png" },
    { price: "3.21", image: "/marquee/image-10.png" },
    { price: "2.22", image: "/marquee/image-11.png" },
    { price: "2.82", image: "/marquee/image-12.png" },
    { price: "1.49", image: "/marquee/image-13.png" },
    { price: "1.57", image: "/marquee/image-14.png" },
    { price: "1.57", image: "/marquee/image-15.png" },
    { price: "1.57", image: "/marquee/image-16.png" },
  ];